# Generated by Django 6.0.3 on 2026-03-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warranty", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warrantycard",
            name="invoice_no",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
